services:
  # MongoDB services
  mongo_db:
    container_name: mymongodb
    ports:
      - 27017:27017
    image: mongo:latest
    restart: always
    volumes:
      - ~/workspace/dataDB:/data/db

  # Node API services
  api:
    build: .
    container_name: myrestapi
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongo_db
