### GET all products
GET http://localhost:3000/products

### GET home 
GET http://localhost:3000/

### GET Query
GET http://localhost:3000/test?name=iMac&price=3999

### GET Router ID
GET http://localhost:3000/test/1234d56c78b9a10/iMac/2999

### POST JSON
POST http://localhost:3000/test
Content-Type: application/json

{
    "name": "Xioami Note 12",
    "price": 399
}

### POST URLENCODED FORM
POST http://localhost:3000/test
Content-Type: application/x-www-form-urlencoded

name=iMac&price=6999

### POST Create a Product
POST http://127.0.0.1:3000/products
Content-Type: application/json

{
    "name": "Samsung Flip Flop",
    "price": 3.99
}

### GET all products
GET http://localhost:3000/products

### POST Create a Product
POST http://127.0.0.1:3000/products
Content-Type: application/json

{
    "name": "iPhone 16 5G",
    "price": 2199
}

### GET all products
GET http://localhost:3000/products

### PATCH a product by id
PATCH  http://localhost:3000/products/6644b8d6d43650d2e6d8dfae
Content-Type: application/json

{
    "price": 999,
    "name": "Samsung Flip Flop"
}

### GET a product by id
GET http://localhost:3000/products/6644b8d6d43650d2e6d8dfae

### DELETE a product by id
DELETE http://localhost:3000/products/663a3cd6df418309534c06cd
